#!/bin/sh

rm -f  src/*.o src/*.so \
       inst/doc/RcppEigen-unitTests.out \
       inst/doc/RcppEigen-unitTests.aux \
       inst/doc/RcppEigen-unitTests.log \
       */*~ *~
rm -rf autom4te.cache
