require("RcppEigen", character=TRUE, quietly=TRUE)
data(Formaldehyde, package="datasets")
(mm <- cbind(1, Formaldehyde$carb))
crossprod(mm)
.Call("crossprod", mm, PACKAGE="RcppEigen")
.Call("crossprod1", mm, PACKAGE="RcppEigen")
tcrossprod(mm)
.Call("tcrossprod", mm, PACKAGE="RcppEigen")
.Call("tcrossprod1", mm, PACKAGE="RcppEigen")
