// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "../inst/include/RcppEigen.h"

using namespace Rcpp;

// fastLm_impl
List fastLm_impl(NumericMatrix Xs, Eigen::Map<Eigen::VectorXd> y, int type);
RcppExport SEXP RcppEigen_fastLm_impl(SEXP XsSEXP, SEXP ySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Xs(XsSEXP );
        Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP );
        Rcpp::traits::input_parameter< int >::type type(typeSEXP );
        List __result = fastLm_impl(Xs, y, type);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// eigen_version
IntegerVector eigen_version(bool single = false);
RcppExport SEXP RcppEigen_eigen_version(SEXP singleSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< bool >::type single(singleSEXP );
        IntegerVector __result = eigen_version(single);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Eigen_SSE
SEXP Eigen_SSE();
RcppExport SEXP RcppEigen_Eigen_SSE() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        SEXP __result = Eigen_SSE();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
