# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigen_version <- function(single) {
    .Call(`_RcppEigen_eigen_version`, single)
}

eigen_version_typed <- function() {
    .Call(`_RcppEigen_eigen_version_typed`)
}

Eigen_SSE <- function() {
    .Call(`_RcppEigen_Eigen_SSE`)
}

#' @rdname RcppEigen_throttle_cores
EigenNbThreads <- function() {
    .Call(`_RcppEigen_EigenNbThreads`)
}

#' @rdname RcppEigen_throttle_cores
EigenSetNbThreads <- function(n) {
    invisible(.Call(`_RcppEigen_EigenSetNbThreads`, n))
}

fastLm_Impl <- function(X, y, type) {
    .Call(`_RcppEigen_fastLm_Impl`, X, y, type)
}

