# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLm_Impl <- function(X, y, type) {
    .Call('RcppEigen_fastLm_Impl', PACKAGE = 'RcppEigen', X, y, type)
}

eigen_version <- function(single) {
    .Call('RcppEigen_eigen_version', PACKAGE = 'RcppEigen', single)
}

Eigen_SSE <- function() {
    .Call('RcppEigen_Eigen_SSE', PACKAGE = 'RcppEigen')
}

